public enum KeynoteScripting: String {
    case MasterSlide = "master slide"
    case Slide = "slide"
    case Theme = "theme"
    case RichText = "rich text"
    case Character = "character"
    case Paragraph = "paragraph"
    case Word = "word"
    case PlaceholderText = "placeholder text"
    case IworkContainer = "iWork container"
    case IworkItem = "iWork item"
    case AudioClip = "audio clip"
    case Shape = "shape"
    case Chart = "chart"
    case Image = "image"
    case Group = "group"
    case Line = "line"
    case Movie = "movie"
    case Table = "table"
    case TextItem = "text item"
    case Range = "range"
    case Cell = "cell"
    case Row = "row"
    case Column = "column"
}
